### ISSUE TITLE
Error happened when I perform the gazebo simulation with 'roslaunch living_lab_robot_bringup bringup_gazebo.launch'

### ISSUE THREAD

**Issue by cjs0818** [cas4x/zipsa#1]
jschoi@ubuntu:~/catkin_ws/src/zipsa/living_lab_robot_moveit_client/src$ roslaunch living_lab_robot_bringup bringup_gazebo.launch
... logging to /home/jschoi/.ros/log/fac4ddda-c1b2-11e9-97f9-001c421bfeaa/roslaunch-ubuntu-24958.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

inconsistent namespace redefinitions for xmlns:xacro:
 old: http://www.ros.org/wiki/xacro
 new: http://ros.org/wiki/xacro (/home/jschoi/catkin_ws/src/realsense-ros/realsense2_description/urdf/_d435.urdf.xacro)
started roslaunch server http://ubuntu:40919/

SUMMARY
========

PARAMETERS
 * /arm1_controller/joint: arm1_joint
 * /arm1_controller/type: position_controll...
 * /arm2_controller/joint: arm2_joint
 * /arm2_controller/type: position_controll...
 * /arm3_controller/joint: arm3_joint
 * /arm3_controller/type: position_controll...
 * /arm4_controller/joint: arm4_joint
 * /arm4_controller/type: position_controll...
 * /arm5_controller/joint: arm5_joint
 * /arm5_controller/type: position_controll...
 * /arm6_controller/joint: arm6_joint
 * /arm6_controller/type: position_controll...
 * /arm_base_controller/joint: arm_base_joint
 * /arm_base_controller/type: position_controll...
 * /arm_controller/joints: ['body_rotate_joi...
 * /arm_controller/type: position_controll...
 * /body_rotate_controller/joint: body_rotate_joint
 * /body_rotate_controller/type: position_controll...
 * /elevation_controller/joint: elevation_joint
 * /elevation_controller/type: position_controll...
 * /gazebo/enable_ros_network: True
 * /gripper_controller/joint: gripper_joint
 * /gripper_controller/type: position_controll...
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /move_group/allow_trajectory_execution: True
 * /move_group/arm/default_planner_config: None
 * /move_group/arm/longest_valid_segment_fraction: 0.005
 * /move_group/arm/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/arm/projection_evaluator: joints(body_rotat...
 * /move_group/capabilities: 
 * /move_group/controller_list: [{'action_ns': 'f...
 * /move_group/disable_capabilities: 
 * /move_group/hand/default_planner_config: 
 * /move_group/hand/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BFMT/balanced: 0
 * /move_group/planner_configs/BFMT/cache_cc: 1
 * /move_group/planner_configs/BFMT/extended_fmt: 1
 * /move_group/planner_configs/BFMT/heuristics: 1
 * /move_group/planner_configs/BFMT/nearest_k: 1
 * /move_group/planner_configs/BFMT/num_samples: 1000
 * /move_group/planner_configs/BFMT/optimality: 1
 * /move_group/planner_configs/BFMT/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMT/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECE/range: 0.0
 * /move_group/planner_configs/BKPIECE/type: geometric::BKPIECE
 * /move_group/planner_configs/BiEST/range: 0.0
 * /move_group/planner_configs/BiEST/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRT/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRT/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRT/init_temperature: 100
 * /move_group/planner_configs/BiTRRT/range: 0.0
 * /move_group/planner_configs/BiTRRT/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRT/type: geometric::BiTRRT
 * /move_group/planner_configs/EST/goal_bias: 0.05
 * /move_group/planner_configs/EST/range: 0.0
 * /move_group/planner_configs/EST/type: geometric::EST
 * /move_group/planner_configs/FMT/cache_cc: 1
 * /move_group/planner_configs/FMT/extended_fmt: 1
 * /move_group/planner_configs/FMT/heuristics: 0
 * /move_group/planner_configs/FMT/nearest_k: 1
 * /move_group/planner_configs/FMT/num_samples: 1000
 * /move_group/planner_configs/FMT/radius_multiplier: 1.1
 * /move_group/planner_configs/FMT/type: geometric::FMT
 * /move_group/planner_configs/KPIECE/border_fraction: 0.9
 * /move_group/planner_configs/KPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECE/goal_bias: 0.05
 * /move_group/planner_configs/KPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECE/range: 0.0
 * /move_group/planner_configs/KPIECE/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECE/range: 0.0
 * /move_group/planner_configs/LBKPIECE/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRT/epsilon: 0.4
 * /move_group/planner_configs/LBTRRT/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRT/range: 0.0
 * /move_group/planner_configs/LBTRRT/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRM/range: 0.0
 * /move_group/planner_configs/LazyPRM/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstar/type: geometric::LazyPR...
 * /move_group/planner_configs/PDST/type: geometric::PDST
 * /move_group/planner_configs/PRM/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRM/type: geometric::PRM
 * /move_group/planner_configs/PRMstar/type: geometric::PRMstar
 * /move_group/planner_configs/ProjEST/goal_bias: 0.05
 * /move_group/planner_configs/ProjEST/range: 0.0
 * /move_group/planner_configs/ProjEST/type: geometric::ProjEST
 * /move_group/planner_configs/RRT/goal_bias: 0.05
 * /move_group/planner_configs/RRT/range: 0.0
 * /move_group/planner_configs/RRT/type: geometric::RRT
 * /move_group/planner_configs/RRTConnect/range: 0.0
 * /move_group/planner_configs/RRTConnect/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTstar/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstar/goal_bias: 0.05
 * /move_group/planner_configs/RRTstar/range: 0.0
 * /move_group/planner_configs/RRTstar/type: geometric::RRTstar
 * /move_group/planner_configs/SBL/range: 0.0
 * /move_group/planner_configs/SBL/type: geometric::SBL
 * /move_group/planner_configs/SPARS/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARS/max_failures: 1000
 * /move_group/planner_configs/SPARS/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARS/stretch_factor: 3.0
 * /move_group/planner_configs/SPARS/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwo/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwo/max_failures: 5000
 * /move_group/planner_configs/SPARStwo/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwo/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwo/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDE/degree: 16
 * /move_group/planner_configs/STRIDE/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDE/goal_bias: 0.05
 * /move_group/planner_configs/STRIDE/max_degree: 18
 * /move_group/planner_configs/STRIDE/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDE/min_degree: 12
 * /move_group/planner_configs/STRIDE/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDE/range: 0.0
 * /move_group/planner_configs/STRIDE/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDE/use_projected_distance: 0
 * /move_group/planner_configs/TRRT/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRT/goal_bias: 0.05
 * /move_group/planner_configs/TRRT/init_temperature: 10e-6
 * /move_group/planner_configs/TRRT/k_constant: 0.0
 * /move_group/planner_configs/TRRT/max_states_failed: 10
 * /move_group/planner_configs/TRRT/min_temperature: 10e-10
 * /move_group/planner_configs/TRRT/range: 0.0
 * /move_group/planner_configs/TRRT/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRT/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.01
 * /move_group/trajectory_execution/controller_connection_timeout: 1200
 * /move_group/zipsa_arm/default_planner_config: None
 * /move_group/zipsa_arm/longest_valid_segment_fraction: 0.005
 * /move_group/zipsa_arm/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/zipsa_arm/projection_evaluator: joints(body_rotat...
 * /omni_base_controller/cmd_vel_timeout: 20.0
 * /omni_base_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
 * /omni_base_controller/publish_cmd: False
 * /omni_base_controller/publish_rate: 50.0
 * /omni_base_controller/publish_wheel_joint_controller_state: False
 * /omni_base_controller/twist_covariance_diagonal: [0.001, 0.001, 10...
 * /omni_base_controller/type: omni_drive_contro...
 * /omni_base_controller/wheel1: omni_wheel_1_joint
 * /omni_base_controller/wheel2: omni_wheel_2_joint
 * /omni_base_controller/wheel3: omni_wheel_3_joint
 * /omni_base_controller/wheel_radius: 0.0635
 * /omni_base_controller/wheel_separation: 0.282
 * /pan_controller/joint: head_pan_joint
 * /pan_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.005
 * /robot_description_kinematics/zipsa_arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/zipsa_arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/zipsa_arm/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/arm1_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm1_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm1_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm1_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm2_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm2_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm2_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm2_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm3_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm3_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm3_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm3_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm4_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm4_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm4_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm4_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm5_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm5_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm5_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm5_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm6_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm6_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm6_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm6_joint/max_velocity: 0.4
 * /robot_description_planning/joint_limits/arm_base_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/arm_base_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/arm_base_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/arm_base_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/body_rotate_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/body_rotate_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/body_rotate_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/body_rotate_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/elevation_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/elevation_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/elevation_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/elevation_joint/max_velocity: 0.04
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /screen_tilt_controller/joint: head_screen_tilt_...
 * /screen_tilt_controller/type: position_controll...
 * /tilt_controller/joint: head_tilt_joint
 * /tilt_controller/type: position_controll...
 * /use_sim_time: True

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [24974]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to fac4ddda-c1b2-11e9-97f9-001c421bfeaa
process[rosout-1]: started with pid [24985]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [24992]
process[gazebo-3]: started with pid [24993]
process[gazebo_gui-4]: started with pid [24998]
process[urdf_spawner-5]: started with pid [25004]
process[controller_spawner-6]: started with pid [25010]
process[move_group-7]: started with pid [25011]
[ INFO] [1566131008.162858407]: Loading robot model 'living_lab_robot'...
[INFO] [1566131008.802277, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [GuiIface.cc:199] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin 
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1566131009.095756498]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1566131009.101351267]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.211.55.18
[ INFO] [1566131009.254715512]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1566131009.257088791]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.211.55.18
[INFO] [1566131009.919074, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1566131009.939684, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1566131010.655375802]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1566131010.657982642]: MoveGroup debug mode is OFF
Starting planning scene monitors...
[ INFO] [1566131010.658028643]: Starting planning scene monitor
[ INFO] [1566131010.660212753]: Listening to '/planning_scene'
[ INFO] [1566131010.660262619]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1566131010.662393736]: Listening to '/collision_object'
[ INFO] [1566131010.669740341]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1566131011.902883529, 65.700000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1566131011.943657507, 65.717000000]: Physics dynamic reconfigure ready.
[INFO] [1566131012.049807, 65.821000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1566131012.567441100, 65.947000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1566131012.567808055, 65.947000000]: Starting Laser Plugin (ns = /)
[ INFO] [1566131012.569255111, 65.947000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1566131012.790733784, 65.947000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1566131012.791078094, 65.947000000]: Starting Laser Plugin (ns = /)
[ INFO] [1566131012.794632565, 65.947000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[INFO] [1566131012.823194, 65.947000]: Spawn status: SpawnModel: Successfully spawned entity
[urdf_spawner-5] process has finished cleanly
log file: /home/jschoi/.ros/log/fac4ddda-c1b2-11e9-97f9-001c421bfeaa/urdf_spawner-5*.log
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[ INFO] [1566131013.778182977, 65.947000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1566131013.781663810, 65.947000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1566131015.408418409, 65.947000000]: Loading gazebo_ros_control plugin
[ INFO] [1566131015.422377448, 65.947000000]: Starting gazebo_ros_control plugin in namespace: 
[ INFO] [1566131015.431282686, 65.947000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ERROR] [1566131015.620757166, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/omni_wheel_1_joint
[ERROR] [1566131015.624125581, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/omni_wheel_3_joint
[ERROR] [1566131015.624958788, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/omni_wheel_2_joint
[ERROR] [1566131015.628006247, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/body_rotate_joint
[ERROR] [1566131015.629259074, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/elevation_joint
[ERROR] [1566131015.630557764, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm_base_joint
[ERROR] [1566131015.635925496, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm1_joint
[ERROR] [1566131015.639553583, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm2_joint
[ERROR] [1566131015.640263044, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm3_joint
[ERROR] [1566131015.640937422, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm4_joint
[ERROR] [1566131015.642481547, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm5_joint
[ERROR] [1566131015.643381310, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/arm6_joint
[ERROR] [1566131015.644990872, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/head_pan_joint
[ERROR] [1566131015.645888408, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/head_screen_tilt_joint
[ERROR] [1566131015.650010145, 65.947000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/head_tilt_joint
[ INFO] [1566131015.659127508, 65.947000000]: Loaded gazebo_ros_control.
[INFO] [1566131015.735817, 65.956000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1566131015.737859, 65.956000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1566131015.739787, 65.956000]: Loading controller: joint_state_controller
[INFO] [1566131015.765068, 65.957000]: Loading controller: body_rotate_controller
[INFO] [1566131015.790328, 65.958000]: Loading controller: elevation_controller
[INFO] [1566131015.814809, 65.959000]: Loading controller: arm_base_controller
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[INFO] [1566131015.831350, 65.960000]: Loading controller: arm1_controller
[INFO] [1566131015.859900, 65.961000]: Loading controller: arm2_controller
[INFO] [1566131015.873096, 65.962000]: Loading controller: arm3_controller
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[INFO] [1566131015.899550, 65.963000]: Loading controller: arm4_controller
[INFO] [1566131015.915837, 65.964000]: Loading controller: arm5_controller
[INFO] [1566131015.933481, 65.965000]: Loading controller: arm6_controller
[INFO] [1566131015.947986, 65.966000]: Loading controller: screen_tilt_controller
[INFO] [1566131015.965621, 65.967000]: Loading controller: pan_controller
[INFO] [1566131015.978406, 65.968000]: Loading controller: tilt_controller
[INFO] [1566131015.990430, 65.969000]: Controller Spawner: Loaded controllers: joint_state_controller, body_rotate_controller, elevation_controller, arm_base_controller, arm1_controller, arm2_controller, arm3_controller, arm4_controller, arm5_controller, arm6_controller, screen_tilt_controller, pan_controller, tilt_controller
[INFO] [1566131016.006708, 65.970000]: Started controllers: joint_state_controller, body_rotate_controller, elevation_controller, arm_base_controller, arm1_controller, arm2_controller, arm3_controller, arm4_controller, arm5_controller, arm6_controller, screen_tilt_controller, pan_controller, tilt_controller
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[ INFO] [1566131020.538241768, 66.546000000]: Listening to '/throttled_depth_registered_points' using message filter with target frame 'base_footprint '
[ INFO] [1566131020.543484394, 66.546000000]: Listening to '/attached_collision_object' for attached collision objects
Planning scene monitors started.
[ INFO] [1566131020.629329893, 66.552000000]: Initializing OMPL interface using ROS parameters
[ERROR] [1566131020.633670298, 66.552000000]: Could not find the planner configuration 'None' on the param server
[ERROR] [1566131020.668568473, 66.555000000]: Could not find the planner configuration 'None' on the param server
[ INFO] [1566131020.700701820, 66.558000000]: Using planning interface 'OMPL'
[ INFO] [1566131020.703383718, 66.558000000]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1566131020.704268595, 66.558000000]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1566131020.704636198, 66.558000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1566131020.706367413, 66.558000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1566131020.707356090, 66.558000000]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1566131020.709037390, 66.558000000]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1566131020.709162218, 66.558000000]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1566131020.709179420, 66.558000000]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1566131020.709216275, 66.558000000]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1566131020.709230291, 66.558000000]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1566131020.709279667, 66.558000000]: Using planning request adapter 'Fix Start State Path Constraints'

**Comment by byeongkyu** [comment]
"No p gain specified for pid. Namespace" -> It is not error.
Could not find the planner configuration 'None' on the param server -> It is not error.

It seems ok for everything. You can control the robot via topic or moveit_rviz.
